version: '3.4'

services:
  registry:
    build:
      context: ./
      dockerfile: ./dockerfile
    restart: always
    image: registry_docker
    container_name: registry_docker
    ports:
      - 5000:5000
    volumes:
      - registry_docker_data:/var/lib/registry

volumes:
  registry_docker_data:
